"""Add deleted flag to locations

Revision ID: c2a47f62c8fe
Revises: 8c090568f29a
Create Date: 2025-05-14 20:02:06.159610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a47f62c8fe'
down_revision = '8c090568f29a'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("UPDATE location SET latitude = 0 WHERE latitude IS NULL")
    op.execute("UPDATE location SET longitude = 0 WHERE longitude IS NULL")
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
